using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;
using DemoFrameWork.UI;

namespace DemoFrameWork.UI.Editor
{
    /// <summary>
    /// 扫描指定目录下带 IScreenController 的预制体，生成 ScreenIds 常量类，便于用常量代替字符串避免写错。
    /// </summary>
    public class ScreenIdProcessor : AssetPostprocessor
    {
        /// <summary>扫描这些目录（及子目录）下带 IScreenController 的预制体生成 ScreenIds。</summary>
        private static readonly string[] UIPrefabFolders = { "Assets/Resources/Prefabs", "Assets/Demos" };
        /// <summary>生成的 ScreenIds 常量类输出目录。</summary>
        private const string UIIdScriptFolder = "Assets/Scripts/Generated";
        private const string ScreenIdScriptName = "ScreenIds";
        private const string ScreenIdScriptNamespace = "DemoFrameWork.Generated";

        [MenuItem("Assets/Create/UI/Re-generate UI ScreenIds")]
        public static void RegenerateScreenIdsAndRefresh()
        {
            RegenerateScreenIds(true);
        }

        private static bool IsPrefabInScanFolders(string path)
        {
            if (path == null || !path.EndsWith(".prefab")) return false;
            foreach (string folder in UIPrefabFolders)
            {
                if (path.StartsWith(folder)) return true;
            }
            return false;
        }

        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets,
            string[] movedAssets, string[] movedFromAssetPaths)
        {
            foreach (string str in importedAssets)
            {
                if (IsPrefabInScanFolders(str))
                {
                    RegenerateScreenIds(true);
                    return;
                }
            }

            foreach (string str in deletedAssets)
            {
                if (IsPrefabInScanFolders(str))
                {
                    RegenerateScreenIds(true);
                    return;
                }
            }

            for (int i = 0; i < movedAssets.Length; i++)
            {
                if (IsPrefabInScanFolders(movedAssets[i]) || IsPrefabInScanFolders(movedFromAssetPaths[i]))
                {
                    RegenerateScreenIds(true);
                    return;
                }
            }
        }

        public static void RegenerateScreenIds(bool refreshAssetDatabase)
        {
            var paths = new Dictionary<string, string>();
            foreach (string folder in UIPrefabFolders)
            {
                string[] guids = AssetDatabase.FindAssets("t:Prefab", new[] { folder });
                foreach (string guid in guids)
                {
                    string path = AssetDatabase.GUIDToAssetPath(guid);
                    var go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                    if (go == null) continue;

                    var screenController = go.GetComponent<IScreenController>();
                    string name = go.name.Replace(" ", string.Empty);
                    if (screenController != null)
                    {
                        if (paths.ContainsKey(name))
                        {
                            Debug.LogError(
                                $"ScreenIdProcessor: 存在同名界面预制体 \"{name}\"！(1){paths[name]} (2){path}");
                        }
                        else
                        {
                            paths.Add(name, path);
                            Debug.Log($"ScreenIdProcessor: 注册 {name} -> {path}");
                        }
                    }
                }
            }

            string scriptPath = Path.Combine(UIIdScriptFolder, ScreenIdScriptName + ".cs");
            if (!Directory.Exists(UIIdScriptFolder))
                Directory.CreateDirectory(UIIdScriptFolder);

            WriteIdClass(paths, scriptPath);
            if (refreshAssetDatabase)
                AssetDatabase.Refresh();
        }

        private static void WriteIdClass(Dictionary<string, string> idPaths, string filePath)
        {
            var sb = new System.Text.StringBuilder();
            sb.AppendLine("// Auto-generated by ScreenIdProcessor. Do not edit by hand.");
            sb.AppendLine();
            sb.AppendLine($"namespace {ScreenIdScriptNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class {ScreenIdScriptName}");
            sb.AppendLine("    {");

            foreach (var kv in idPaths)
            {
                string id = kv.Key;
                string value = kv.Value;
                sb.AppendLine($"        public const string {id} = \"{id}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(filePath, sb.ToString());
        }
    }
}
